# Generated by Django 2.2 on 2019-04-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cergen', '0002_referenceequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('principle', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Principle',
            },
        ),
    ]
