# Generated by Django 2.2 on 2019-05-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cergen', '0003_principle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Accessory',
            },
        ),
        migrations.CreateModel(
            name='CalibrationRangeUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'CalibrationRangeUnits',
            },
        ),
        migrations.CreateModel(
            name='MeasuringRangeUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'MeasuringRangeUnits',
            },
        ),
        migrations.CreateModel(
            name='OutputSignalUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'OutputSignalUnits',
            },
        ),
    ]
